apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "mkdir -p /var/cache/nginx/client_temp && chmod -R 777 /var/cache/nginx"]
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}